import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'New Next App',
  description: 'Generated by create next app',
}

export default function page() {
  return (
    <div>page</div>
  )
}
